// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsmgwtjgnlezzihsvjtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbWd3dGpnbmxlenppaHN2anR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODA0ODUsImV4cCI6MjA3MzY1NjQ4NX0.8TvkDhUCbRGmFWZ1OXUh2UwjMqlpqp3FwZn7mrtlH4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});